<template>
   <ul class="content">
       <li>列表数字：1</li>
       <li>列表数字：2</li>
       <li>列表数字：3</li>
       <li>列表数字：4</li>
       <li>列表数字：5</li>
       <li>列表数字：6</li>
       <li>列表数字：7</li>
       <li>列表数字：8</li>
       <li>列表数字：9</li>
       <li>列表数字：10</li>
       <li>列表数字：11</li>
       <li>列表数字：12</li>
       <li>列表数字：13</li>
       <li>列表数字：14</li>
       <li>列表数字：15</li>
       <li>列表数字：16</li>
       <li>列表数字：17</li>
       <li>列表数字：18</li>
       <li>列表数字：19</li>
       <li>列表数字：20</li>
       <li>列表数字：21</li>
       <li>列表数字：22</li>
       <li>列表数字：23</li>
       <li>列表数字：24</li>
       <li>列表数字：25</li>
       <li>列表数字：26</li>
       <li>列表数字：27</li>
       <li>列表数字：28</li>
       <li>列表数字：29</li>
       <li>列表数字：30</li>
       <li>列表数字：31</li>
       <li>列表数字：32</li>
       <li>列表数字：33</li>
       <li>列表数字：34</li>
       <li>列表数字：35</li>
       <li>列表数字：36</li>
       <li>列表数字：37</li>
       <li>列表数字：38</li>
       <li>列表数字：39</li>
       <li>列表数字：40</li>
       <li>列表数字：41</li>
       <li>列表数字：42</li>
       <li>列表数字：43</li>
       <li>列表数字：44</li>
       <li>列表数字：45</li>
       <li>列表数字：46</li>
       <li>列表数字：47</li>
       <li>列表数字：48</li>
       <li>列表数字：49</li>
       <li>列表数字：50</li>
       <li>列表数字：51</li>
       <li>列表数字：52</li>
       <li>列表数字：53</li>
       <li>列表数字：54</li>
       <li>列表数字：55</li>
       <li>列表数字：56</li>
       <li>列表数字：57</li>
       <li>列表数字：58</li>
       <li>列表数字：59</li>
       <li>列表数字：60</li>
       <li>列表数字：61</li>
       <li>列表数字：62</li>
       <li>列表数字：63</li>
       <li>列表数字：64</li>
       <li>列表数字：65</li>
       <li>列表数字：66</li>
       <li>列表数字：67</li>
       <li>列表数字：68</li>
       <li>列表数字：69</li>
       <li>列表数字：70</li>
       <li>列表数字：71</li>
       <li>列表数字：72</li>
       <li>列表数字：73</li>
       <li>列表数字：74</li>
       <li>列表数字：75</li>
       <li>列表数字：76</li>
       <li>列表数字：77</li>
       <li>列表数字：78</li>
       <li>列表数字：79</li>
       <li>列表数字：80</li>
       <li>列表数字：81</li>
       <li>列表数字：82</li>
       <li>列表数字：83</li>
       <li>列表数字：84</li>
       <li>列表数字：85</li>
       <li>列表数字：86</li>
       <li>列表数字：87</li>
       <li>列表数字：88</li>
       <li>列表数字：89</li>
       <li>列表数字：90</li>
       <li>列表数字：91</li>
       <li>列表数字：92</li>
       <li>列表数字：93</li>
       <li>列表数字：94</li>
       <li>列表数字：95</li>
       <li>列表数字：96</li>
       <li>列表数字：97</li>
       <li>列表数字：98</li>
       <li>列表数字：99</li>
       <li>列表数字：100</li>
   </ul>
</template>
<script>
export default {
    name:'category',
    
}
</script>

<style scoped>
.content{
    height: 150px;
    background-color: red;
    overflow: hidden;
    overflow-y:scroll;
}
</style>